### ISSUE TITLE
quest!

### ISSUE THREAD

**Issue by MuhunKim** [MuhunKim/npm-gulp-es2015-boilerplate#4]
@kshinlee @gyuho26 @Kangmin93 `README.md` 에서 고쳐야 될 부분을 찾아보세요!
# `$ npm run test`
1. 윈도우 환경에서는 http://0.0.0.0:8080 이 정상적으로 작동되지 않습니다. 대신 뭘로 해야 할까요?
2. 테스트시 윈도우 환경에서는 크롬 환경 변수를 설정해야 됩니다. 환경변수 설정 명령어를 찾아보세요.

답은 [Issues](https://github.com/JeffGuKang/npm-webpack-boilerplate/issues?q=is%3Aopen+is%3Aissue)와 [Pull-Request](https://github.com/JeffGuKang/npm-webpack-boilerplate/pulls)에서 찾아보시길 바랍니다.

**Comment by gyuho26** [comment]
1.  http://localhost:8080
2. CHROME_BIN
확실한 건지는...
